### PR TITLE
overview update

### PR DESCRIPTION
**Pull request by wiktormowinski**

### CODE REVIEW

**Comment by macpijan** [comment]
@wiktormowinski do you think you can fix the linchecker problem as well?

**Comment by wiktormowinski** [comment]
sure @macpijan all good now

**Comment by wiktormowinski** [comment]
should i get the commits squashed before merging? @macpijan

**Comment by mkopec** [comment]
@wiktormowinski yes, please let's squash the commits, and rebase to resolve conflicts

**Review by mkopec — APPROVED** [review]
thanks, looks good now

**Pull request merged**
