### PR TITLE
novacustom_nv4x_tgl/test-matrix.md: updated test cases

### PR DESCRIPTION
**Pull request by Mixss**

### CODE REVIEW

**Comment by miczyg1** [comment]
Aren't these tests supposed to be run on all models?

**Comment by Mixss** [comment]
@miczyg1 This pull request is made strictly for nv4x_tgl

**Comment by miczyg1** [comment]
> @miczyg1 This pull request is made strictly for nv4x_tgl

We should have feature parity across all models, so please add the same tests for other models as well @Mixss

**Comment by macpijan** [comment]
This has been already covered in: https://github.com/Dasharo/docs/pull/651/files

**Pull request closed without merging**
