### PR TITLE
add 12700k hcl

### PR DESCRIPTION
**Pull request by mwikman**
Adds 12700k to the cpu HCL with linked Qubes HCL

Signed-off-by: Michael Wikman <michaelwikman95@gmail.com>

### CODE REVIEW

**Comment by miczyg1** [comment]
@mwikman thank you for your contribution. Mind adding an entry to the [memory-hcl.md](https://github.com/Dasharo/docs/blob/master/docs/variants/msi_z690/memory-hcl.md) and [gpu-hcl.md](https://github.com/Dasharo/docs/blob/master/docs/variants/msi_z690/gpu-hcl.md) too?

**Comment by miczyg1** [comment]
@mwikman do you have a GPG key added to GitHub possibly? Our checks indicate that your commit is not signed.

**Comment by mwikman** [comment]
@miczyg1 i do not but ill set it up for the next one

**Comment by miczyg1** [comment]
@mwikman thanks, appreciate it. Would be great to have the commits signed.

**Pull request merged**
