### PR TITLE
v1x10: add board to docs

### PR DESCRIPTION
**Pull request by pkubaj**
Signed-off-by: Piotr Kubaj <piotr.kubaj@3mdeb.com>

### CODE REVIEW

**Comment by macpijan** [comment]
This should wait until these are official released by Protectli

**Comment by pkubaj** [comment]
Jira task specifies that those boards should be added to docs, hence I sent this PR.

**Comment by macpijan** [comment]
It does not hurt, just saying we simply should wait prior merging.

**Comment by philipandag** [comment]
This PR is addressed in the process of protectli docs reorganisation https://github.com/Dasharo/docs/pull/851/files#diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2R278-R280

**Pull request closed without merging**
