### PR TITLE
Add NovaCustom NS5X documentation

### PR DESCRIPTION
**Pull request by mkopec**
Based on the Tuxedo IBS15 docs.

Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>

### CODE REVIEW

**Comment by macpijan** [comment]
@mkopec rebase is necessary

**Comment by mkopec** [comment]
@macpijan rebased

**Comment by mkopec** [comment]
@macpijan updated initial deployment instructions and rebased again

**Comment by mkopec** [comment]
Also added v1.0.0 release info

**Comment by mkopec** [comment]
Rebased and updated initial installation instructions

**Pull request merged**
