### PR TITLE
docs/osf-trivia-list/dasharo.md: add section about porting Dasharo

### PR DESCRIPTION
**Pull request by miczyg1**

### CODE REVIEW

**Review by pietrushnic — APPROVED** [review]
@miczyg1 let me know what do you think.

**Comment by pietrushnic** [comment]
@miczyg1 make sense, do you want to write paragraph about that? Does it fit here? Maybe it is more Dasharo Community Support definition?

**Comment by miczyg1** [comment]
> @miczyg1 make sense, do you want to write paragraph about that? Does it fit here? Maybe it is more Dasharo Community Support definition?

Could be a part of Dasharo Community Support definition, indeed. But this is subject to another PR I think? We can always extend the Dasharo porting section nonce we have a Dasharo Community Support definition.

**Comment by pietrushnic** [comment]
@miczyg1 yes, "what is DCS" is in comment at this point. Let's finish what is already in progress and we can back to commented questions later.

**Review by pietrushnic — APPROVED** [review]

**Pull request merged**
