### PR TITLE
added_references

### PR DESCRIPTION
**Pull request by Stanislaw-bnk**

### CODE REVIEW

**Review by artur-rs — APPROVED** [review]

**Comment by artur-rs** [comment]
@Stanislaw-bnk there is only 1 step missing, please sign your commits

**Comment by macpijan** [comment]
@Stanislaw-bnk Thanks for these improvements. Please sign commits as requested by Artur above.

**Comment by macpijan** [comment]
@Stanislaw-bnk reminder ping

**Comment by Stanislaw-bnk** [comment]
@macpijan I've tried to sign the commits but to do so, I requested a help from @artur-rs. Unfortunately, he didn't manage to find time before his vacation.

**Comment by pietrushnic** [comment]
@Stanislaw-bnk please refer to publicly available documentation. In 3mdeb there are also other people who can help you solve this minor issue.

**Pull request merged**
