### PR TITLE
Vp2420 release v1.1.0 documentation update

### PR DESCRIPTION
**Pull request by Pokisiekk**

### CODE REVIEW

**Comment by miczyg1** [comment]
We also have to update UEFI Secure Boot instructions. Now one has to reset the keys to defaults first before secure boot attempt can be selected

**Comment by Pokisiekk** [comment]
@miczyg1 Where exactly is this information missing?
https://docs.dasharo.com/dasharo-menu-docs/device-manager/#secure-boot-configuration - Here is how it works
https://docs.dasharo.com/unified-test-documentation/dasharo-security/206-secure-boot/ - And in test cases, we link to the above-linked documentation

**Review by sulewskiprzemyslaw — APPROVED** [review]

**Comment by miczyg1** [comment]
@Pokisiekk I meant test cases SBO002.001 and SBO002.002. The procedure says `select the Attempt Secure Boot` in point 5 but it doesn't handle situation when you boot for the first time and keys are not enrolled. In that case the `Attempt Secure Boot` option will be inactive

**Comment by Pokisiekk** [comment]
@miczyg1 In `Test Setup` section, 4th step says:
* Proceed with the [Secure Boot Configuration](https://docs.dasharo.com/dasharo-menu-docs/device-manager/#secure-boot-configuration) to enable the Attempt Secure Boot option in the Secure Boot Configuration menu.

**Comment by miczyg1** [comment]
> @miczyg1 In `Test Setup` section, 4th step says:
> 
> * Proceed with the [Secure Boot Configuration](https://docs.dasharo.com/dasharo-menu-docs/device-manager/#secure-boot-configuration) to enable the Attempt Secure Boot option in the Secure Boot Configuration menu.

I see ,thanks.

**Pull request merged**
