### PR TITLE
variants/{novacustom_ns5x,tuxedo_ibs15}: flash the COREBOOT region

### PR DESCRIPTION
**Pull request by mkopec**
Vboot was disabled on these laptops, so the flashing instructions need to be updated.

Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>

### CODE REVIEW

**Comment by mkopec** [comment]
@macpijan ping

**Review by macpijan — CHANGES_REQUESTED** [review]
If the procedure is different depending on the version, maybe we should have both methods and indicate which version support which method.

**Comment by macpijan** [comment]
@mkopec

**Comment by mkopec** [comment]
@macpijan Updated. For NVC NS5x, Dasharo v1.1.0 and newer has Vboot disabled. Tuxedo IBS15 without Vboot wasn't released yet, so for now I reverted the command  back to `--ifd -i bios`

**Review by macpijan — APPROVED** [review]

**Comment by macpijan** [comment]
picked in: https://github.com/Dasharo/docs/pull/333

**Pull request closed without merging**
