### PR TITLE
Typo fix: hurts -> hurt

### PR DESCRIPTION
**Pull request by blegat**

### CODE REVIEW

**Review by pietrushnic — APPROVED** [review]
@blegat thank you very much for your contribution.

**Review by macpijan — APPROVED** [review]

**Comment by macpijan** [comment]
@blegat Would you mind signing your commit with GPG key? If you do not feel like it, I can also cherry pick that with my signature.

**Comment by blegat** [comment]
Sure, it is now signed

**Comment by macpijan** [comment]
Thank you @blegat

**Pull request merged**
