### PR TITLE
docs/unified/novacustom/battery-management.md: added / inside paths t…

### PR DESCRIPTION
**Pull request by johanes2115**
…o images

### CODE REVIEW

**Review by mkopec — APPROVED** [review]

**Comment by mkopec** [comment]
@johanes2115 Needs a rebase I think

**Comment by mkopec** [comment]
Closing, as this was fixed elsewhere already.

**Comment by macpijan** [comment]
@mkopec 

> Closing, as this was fixed elsewhere already.

It would be nice to provide a link for reference, in cases like this.

**Comment by mkopec** [comment]
@macpijan Right. This was fixed by https://github.com/Dasharo/docs/commit/4e43a6e3d7d76f722412a15cdc003d94f16fa412 .

**Pull request closed without merging**
